# Generated by Django 3.1.7 on 2022-08-22 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalleorden',
            fields=[
                ('detalleid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.BigIntegerField()),
            ],
            options={
                'db_table': 'detalleorden',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('estadoid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'estado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estadoorden',
            fields=[
                ('estadoordenid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'estadoorden',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ordencompra',
            fields=[
                ('ordenid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fechapedido', models.DateField()),
            ],
            options={
                'db_table': 'ordencompra',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Detallepedido',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
