# Generated by Django 3.2 on 2022-10-21 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalleventa',
            fields=[
                ('detalleventaid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.BigIntegerField()),
                ('subtotal', models.BigIntegerField()),
            ],
            options={
                'db_table': 'detalleventa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipopago',
            fields=[
                ('tipopagoid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'tipopago',
                'managed': False,
            },
        ),
    ]
