# Generated by Django 4.1 on 2022-08-19 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Despacho',
        ),
    ]
