# Generated by Django 3.1.7 on 2022-10-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_detalleventa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipopago',
            fields=[
                ('tipopagoid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'tipopago',
                'managed': False,
            },
        ),
    ]
