# Generated by Django 4.1 on 2022-08-24 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_auto_20220821_2028'),
        ('src', '0002_delete_despacho'),
    ]

    operations = [
    ]
