# Generated by Django 4.1 on 2022-08-24 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_merge_0002_auto_20220821_2028_0002_delete_despacho'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('despachoid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fechasolicitud', models.DateField()),
                ('fechadespacho', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'despacho',
                'managed': False,
            },
        ),
    ]
