# Generated by Django 4.1 on 2022-09-01 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_despacho'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('cargoid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'cargo',
                'managed': False,
            },
        ),
    ]
