# Generated by Django 4.1 on 2022-10-05 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('menu', models.CharField(max_length=200)),
                ('accion', models.CharField(max_length=250)),
                ('usuario', models.BigIntegerField()),
            ],
            options={
                'db_table': 'auditoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('pasillo', models.CharField(max_length=6)),
                ('estante', models.CharField(max_length=6)),
                ('casillero', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'bodega',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Direccioncliente',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'direccioncliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('rutina', models.CharField(max_length=150)),
                ('mensaje', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'error',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productoproveedor',
            fields=[
                ('ProId', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'productoproveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ventadiaria',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('totalventa', models.BigIntegerField()),
            ],
            options={
                'db_table': 'ventadiaria',
                'managed': False,
            },
        ),
    ]
